#version 450 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// 粒子结构体
struct Particle {
    vec2 position;
    vec2 velocity;
    vec4 color;
};

// SSBO 槽位 0: 粒子总池 (只读位置数据)
layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

// SSBO 槽位 1: 网格表头数组 (Grid Head)。存的是每个格子里 "最新的那个粒子的 ID"
layout(std430, binding = 1) buffer GridHeadBuffer {
    int gridHead[];
};

// SSBO 槽位 2: 粒子链表数组 (Linked List)。存的是 "跟我同格的下一个粒子的 ID"
layout(std430, binding = 2) buffer LinkedListBuffer {
    int particleList[];
};

// C++ 传进来的控制参数
uniform int u_ParticleCount;
uniform ivec2 u_GridSize; // 网格划分的密度，比如 (128, 128)

void main() {
    uint myID = gl_GlobalInvocationID.x;
    if (myID >= u_ParticleCount) return;

    if (particles[myID].position.x > 10.0) return;

    // 1. 获取我的坐标，并将其从 [-1.0, 1.0] 映射到 [0.0, 1.0]
    vec2 pos = particles[myID].position;
    vec2 normPos = clamp((pos + 1.0) * 0.5, 0.0, 1.0);

    // 2. 计算我属于二维网格的哪个格子 (x, y)
    // 注意：用 min 防止极度贴边的粒子越界
    ivec2 cell = ivec2(normPos * vec2(u_GridSize));
    cell = clamp(cell, ivec2(0), u_GridSize - ivec2(1));

    // 3. 将二维格子坐标展平为一维数组索引
    int gridIndex = cell.y * u_GridSize.x + cell.x;

    // 4. 【神级操作：原子交换】
    // 强制把 gridHead[gridIndex] 设为我的 myID。
    // 同时，把这个格子里原本存的 ID (也就是上一个路过这个格子的粒子 ID) 返回给我。
    int oldHeadID = atomicExchange(gridHead[gridIndex], int(myID));

    // 5. 顺藤摸瓜：把这个旧的 ID 存到我的链表节点里。
    // 这样以后别人查到我，就能顺着我找到原来那个粒子！
    particleList[myID] = oldHeadID;
}